In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
df = pd.read_csv('Student Mental Health Analysis During Online Learning.csv')
df.head()

,Name,Gender,Age,Education Level,Screen Time (hrs/day),Sleep Duration (hrs),Physical Activity (hrs/week),Stress Level,Anxious Before Exams,Academic Performance Change
0,Aarav,Male,15,Class 8,7.1,8.9,9.3,Medium,No,Same
1,Meera,Female,25,MSc,3.3,5.0,0.2,Medium,No,Same
2,Ishaan,Male,20,BTech,9.5,5.4,6.2,Medium,No,Same
3,Aditya,Male,20,BA,10.8,5.6,5.5,High,Yes,Same
4,Anika,Female,17,Class 11,2.8,5.4,3.1,Medium,Yes,Same

In [25]:
df.shape

(1000, 10)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Name                          1000 non-null   object
 1   Gender                        1000 non-null   object
 2   Age                           1000 non-null   int64
 3   Education Level               1000 non-null   object
 4   Screen Time (hrs/day)         1000 non-null   float64
 5   Sleep Duration (hrs)          1000 non-null   float64
 6   Physical Activity (hrs/week)  1000 non-null   float64
 7   Stress Level                  1000 non-null   object
 8   Anxious Before Exams          1000 non-null   object
 9   Academic Performance Change   1000 non-null   object
dtypes: float64(3), int64(1), object(6)
memory usage: 78.3+ KB

In [27]:
df['Stress Level'].value_counts()

Stress Level
Medium    492
Low       327
High      181
Name: count, dtype: int64

In [28]:
df['Stress Level'] = df['Stress Level'].map({"Low":1, "Medium" :2, "High" :3})

In [29]:
df['Gender'] = df['Gender'].map({"Male": 1, "Female" :0})
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

In [30]:
df['Anxious Before Exams'] = df['Anxious Before Exams'].map({"Yes": 1, "No" :0})

In [31]:
df.head()

,Name,Gender,Age,Education Level,Screen Time (hrs/day),Sleep Duration (hrs),Physical Activity (hrs/week),Stress Level,Anxious Before Exams,Academic Performance Change
0,Aarav,1.0,15,Class 8,7.1,8.9,9.3,2,0,Same
1,Meera,0.0,25,MSc,3.3,5.0,0.2,2,0,Same
2,Ishaan,1.0,20,BTech,9.5,5.4,6.2,2,0,Same
3,Aditya,1.0,20,BA,10.8,5.6,5.5,3,1,Same
4,Anika,0.0,17,Class 11,2.8,5.4,3.1,2,1,Same

In [32]:
df['Academic Performance Change'].value_counts()

Academic Performance Change
Same        399
Improved    303
Declined    298
Name: count, dtype: int64

In [33]:
df['Academic Performance Change'] = df['Academic Performance Change'].map({
    "Same" : 0,
    "Improved" : 1,
    "Declined" : -1
})

In [34]:
df

,Name,Gender,Age,Education Level,Screen Time (hrs/day),Sleep Duration (hrs),Physical Activity (hrs/week),Stress Level,Anxious Before Exams,Academic Performance Change
0,Aarav,1.0,15,Class 8,7.1,8.9,9.3,2,0,0
1,Meera,0.0,25,MSc,3.3,5.0,0.2,2,0,0
2,Ishaan,1.0,20,BTech,9.5,5.4,6.2,2,0,0
3,Aditya,1.0,20,BA,10.8,5.6,5.5,3,1,0
4,Anika,0.0,17,Class 11,2.8,5.4,3.1,2,1,0
...,...,...,...,...,...,...,...,...,...,...
995,Diya,0.0,26,MA,11.3,6.8,9.1,2,0,0
996,Aarav,1.0,20,BTech,5.5,6.7,6.8,1,1,0
997,Myra,0.0,15,Class 9,7.1,4.1,1.9,1,1,-1
998,Myra,0.0,20,BA,4.4,7.5,4.5,2,0,1
999,Vihaan,1.0,23,MA,10.8,7.7,3.6,1,0,1

In [35]:
df['Education Level'].value_counts()

Education Level
MTech       143
MSc         138
MA          129
Class 11     88
Class 9      87
Class 10     87
BSc          85
BTech        84
BA           62
Class 8      50
Class 12     47
Name: count, dtype: int64

In [36]:
def classify_education(x):
    if x in ['Class 8','Class 9','Class 10','Class 11','Class 12']:
        return 'School'
    elif x in ['BA','BSc','BTech']:
        return 'Undergraduate'
    elif x in ['MA','MSc','MTech']:
        return 'Postgraduate'

df['Education_Category'] = df['Education Level'].apply(classify_education)

In [37]:
education_map = {
    'Class 8':'School',
    'Class 9':'School',
    'Class 10':'School',
    'Class 11':'School',
    'Class 12':'School',
    'BA':'Undergraduate',
    'BSc':'Undergraduate',
    'BTech':'Undergraduate',
    'MA':'Postgraduate',
    'MSc':'Postgraduate',
    'MTech':'Postgraduate'
}

df['Education_Category'] = df['Education Level'].map(education_map)

In [38]:
df['Education_Category']

0             School
1       Postgraduate
2      Undergraduate
3      Undergraduate
4             School
           ...
995     Postgraduate
996    Undergraduate
997           School
998    Undergraduate
999     Postgraduate
Name: Education_Category, Length: 1000, dtype: object

In [39]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["Education_Category"] = le.fit_transform(df["Education_Category"])

In [63]:
df["Education_Category"].value_counts()

Education_Category
0    410
1    359
2    231
Name: count, dtype: int64

In [41]:
df.drop('Education Level', axis=1, inplace=True)

In [42]:
df.drop(['Name'], axis=1,inplace=True)

In [43]:
df.isnull().sum()

Gender                          0
Age                             0
Screen Time (hrs/day)           0
Sleep Duration (hrs)            0
Physical Activity (hrs/week)    0
Stress Level                    0
Anxious Before Exams            0
Academic Performance Change     0
Education_Category              0
dtype: int64

In [44]:
X = df.drop(['Stress Level'], axis= 1)
y = df['Stress Level']

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [47]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

RandomForestClassifier()

In [48]:
y_pred = model.predict(X_test)

In [49]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.405

In [50]:
importance = model.feature_importances_
features = X.columns

pd.DataFrame({
    "Feature": features,
    "Importance": importance
}).sort_values(by="Importance", ascending=False)

                        Feature  Importance
4  Physical Activity (hrs/week)    0.235797
2         Screen Time (hrs/day)    0.230329
3          Sleep Duration (hrs)    0.225478
1                           Age    0.132775
6   Academic Performance Change    0.063527
5          Anxious Before Exams    0.038790
7            Education_Category    0.037150
0                        Gender    0.036154

only taking importance features

In [53]:
X_imp = df[['Physical Activity (hrs/week)',
        'Screen Time (hrs/day)',
        'Sleep Duration (hrs)',
        'Age',
        'Education_Category']]
y = df['Stress Level']

In [54]:
df['Stress Level'].value_counts()

Stress Level
2    492
1    327
3    181
Name: count, dtype: int64

In [55]:

X_train, X_test, y_train, y_test = train_test_split(X_imp, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [56]:
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.515

In [57]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[26, 41,  1],
       [20, 76,  2],
       [ 8, 25,  1]])

In [58]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.48      0.38      0.43        68
           2       0.54      0.78      0.63        98
           3       0.25      0.03      0.05        34

    accuracy                           0.52       200
   macro avg       0.42      0.40      0.37       200
weighted avg       0.47      0.52      0.46       200

In [59]:
def give_recommendations(data):
    
    recommendations = []
    
    if data["Screen Time (hrs/day)"] > 6:
        recommendations.append("Reduce screen time to less than 5 hours per day.")
        
    if data["Sleep Duration (hrs)"] < 7:
        recommendations.append("Try to maintain at least 7–8 hours of sleep.")
        
    if data["Physical Activity (hrs/week)"] < 3:
        recommendations.append("Increase physical activity to at least 3–5 hours per week.")
        
    if len(recommendations) == 0:
        recommendations.append("Your lifestyle looks healthy. Keep maintaining it!")
        
    return recommendations

In [61]:
import joblib

In [62]:

joblib.dump(model,"student_stress_model.pkl")

['student_stress_model.pkl']